---
- name: Set SA telemetry project
  oc_project:
    state: present
    name: "{{ sa_telemetry_namespace }}"
    node_selector: "{{ sa_telemetry_nodeselector }}"
  run_once: true

- name: Add login information to masters htpasswd
  template:
    src: origin_master_htpasswd.j2
    dest: /etc/origin/master/htpasswd

- name: Create users in OpenShift
  oc_user:
    state: present
    username: "{{ item.name }}"
  with_items: "{{ sa_telemetry_users }}"
  run_once: true

- name: Apply roles to users in OpenShift
  oc_adm_policy_user:
    state: present
    user: "{{ item.name }}"
    namespace: "{{ sa_telemetry_postinstall_namespace }}"
    resource_kind: cluster-role
    resource_name: cluster-admin
  with_items: "{{ sa_telemetry_users }}"
  run_once: true
