- name: Update sysctl values for ElasticSearch
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    sysctl_set: yes
    reload: yes

- name: Set rmem_max for QDRs
  sysctl:
    name: net.core.rmem_max
    value: 134217728
    state: present
    sysctl_set: yes
    reload: yes

- name: Set tcp_rmem for QDRs
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "10240 33554432 134217728"
    state: present
    sysctl_set: yes
    reload: yes
