---
- name: oVirt infra
  hosts: engine
  gather_facts: false

  vars:
    vm_state: absent

  vars_files:
    # Contains encrypted `engine_password` variable using ansible-vault
    - ../vars/{{ password_file }}

  tasks:
    - include_role:
        name: oVirt.vm-infra
      tags:
        - install-vm-infra
